name: fib.py

on:
  pull_request:
    branches:
      - master
    paths:
      - "fib/*.py"
      - "fib/install_deps.sh"
      - "fib/Makefile"
      - ".github/workflows/fib-py.yml"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Test fib.py
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fib
    steps:
      - uses: actions/checkout@v5

      - name: Install Python dependencies
        run: pip install ruff coverage

      - name: Run tests
        run: make test
