name: sq-rs

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    name: Test sq-rs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sq/sq-rs
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: sq/sq-rs

      - name: Run tests
        run: make test

  build:
    name: Build sq-rs
    runs-on: ubuntu-latest
    needs: [test]
    defaults:
      run:
        working-directory: sq/sq-rs
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: sq/sq-rs

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: sq
          path: sq/sq-rs/target/release/sq
          retention-days: 7
